# Site settings
title: ktewelde
email: kteweldebrhane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Web developer, eCommerce developer, Web application developer, freelancer, website developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ktewelde.co.uk/" # the base hostname & protocol for your site
twitter_username: username
github_username: kiflay

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
plugins:
  - jekyll-sitemap
 
 